### ISSUE TITLE
SMS verification page should have "SMS verification code" as place holder rather than "2FA code" currently there :nerd_face: 

### ISSUE THREAD

**Issue by PromiseFru** [smswithoutborders/smswithoutborders.com#22]

**Comment by nSedrickm** [comment]
Hello @MahmoudHamdy02, thanks for fixing this so fast. The most recent changes to this project can be found in the [#dev](https://github.com/smswithoutborders/smswithoutborders.com/tree/dev). I encourage you to branch from there and make these changes then open a new pull request to the #dev branch. Thank you

**Comment by MahmoudHamdy02** [comment]
No problem! I'm new to open source so I'll be on the lookout for more simple issues in the future.

**Comment by nSedrickm** [comment]
That is great. Let me know if you need help. You can take a look at our [contribution guide](https://github.com/smswithoutborders/smswithoutborders.com/blob/dev/docs/CONTRIBUTING.md) to help you get started with the project

**Comment by nSedrickm** [comment]
For this issue, these are the pages you can make the changes to:

* [signup code verification page](https://github.com/smswithoutborders/smswithoutborders.com/blob/dev/src/pages/signup/CodeVerification.js)
* [telegram code verification page](https://github.com/smswithoutborders/smswithoutborders.com/blob/dev/src/pages/Wallet/telegram/CodeVerification.js)
* [password reset code verification page](https://github.com/smswithoutborders/smswithoutborders.com/blob/dev/src/pages/password-reset/CodeVerification.js)

**Comment by nSedrickm** [comment]
@PromiseFru this is fixed by #25
