### ISSUE TITLE
Low site performance and accessibility scores

### ISSUE THREAD

**Issue by teyim** [smswithoutborders/smswithoutborders.com#38]
![bandicam 2022-06-15 16-40-15-878](https://user-images.githubusercontent.com/48864977/173856824-45286f68-1d01-42b2-b800-5e596875a959.jpg)

**Comment by nSedrickm** [comment]
Hi @teyim, thanks for catching this.

Sure, it will be great if you could. However, I recommend you work with the [dev](https://github.com/smswithoutborders/smswithoutborders.com/tree/dev) branch since it has the most recent changes

Also, be sure to checkout our [contribution guide](https://github.com/smswithoutborders/smswithoutborders.com/blob/dev/docs/CONTRIBUTING.md) to help you get started

Let me know if you have any questions

**Comment by teyim** [comment]
ok

**Comment by nSedrickm** [comment]
Hello @teyim. Will you be going forward with this issue?

**Comment by teyim** [comment]
Hey @nSedrickm ..so sorry about this. Yes, I will.

**Comment by nSedrickm** [comment]
Ok

**Comment by teyim** [comment]
Hey, @nSedrickm got some issues while working on this. Firstly, the lighthouse report shows that the 2 main performance issues are
1. Large content paint  
2. Some resources blocking the first content paint of the page

Looking at this we see that the main possible fixes as suggested by the lighthouse are reducing unused js,eliminate content blocking resources, and eliminating the largest content paint image. Now, comparing our image sizes with optimized webp images, there is little or no difference in size, so I think the image sizes are not really an issue here.
Also running a lighthouse diagnosis on the prod build served locally, I get the following results:
![bandicam 2022-07-20 15-16-51-543](https://user-images.githubusercontent.com/48864977/179995973-b25ff8e8-5e08-421f-b955-4ae6817e4f5a.jpg)
which is a little bit confusing since it shows clearly that, large content paint is not an issue, making it difficult to actually fix this issue.
will love your help on this.

**Comment by nSedrickm** [comment]
Hello @teyim. Thanks for these findings.

We could try optimizing the sites routing. Currently we are only lazy loading the entire app bundle in [index.js](https://github.com/smswithoutborders/smswithoutborders.com/blob/dev/src/pages/index.js)

Perhaps it will be more performant to lazyload all pages individually. You can take a closer look in [App.js](https://github.com/smswithoutborders/smswithoutborders.com/blob/dev/src/App.js) where all the routes are defined and the [pages](https://github.com/smswithoutborders/smswithoutborders.com/tree/dev/src/pages) folder for all the pages

**Comment by teyim** [comment]
Ok,this sounds promising..let me look into it .

**Comment by teyim** [comment]
Hey @nSedrickm ,i have opened a PR for this.please review

**Comment by nSedrickm** [comment]
Thanks @teyim merged in #43. This issue can be closed
