### ISSUE TITLE
docs: change master to main

### ISSUE THREAD

**Issue by nSedrickm** [smswithoutborders/SMSWithoutBorders.com#58]
We renamed our master branch to main.

Some of our docs still refrence the master branch and it will be great to have them changed to main

**Comment by giftade** [comment]
I'd like to do this

**Comment by nSedrickm** [comment]
Hello @giftade, glad to have you here!

Please take a look at our[ contribution guide](https://github.com/smswithoutborders/smswithoutborders.com/blob/dev/docs/CONTRIBUTING.md) to get started.

Let me know if you need any help

**Comment by teyim** [comment]
Hello @nSedrickm is this still open?,would want to work on this.

**Comment by nSedrickm** [comment]
Hi @teyim not sure, perhaps @giftade is currently working on it. @giftade do you need any help?

**Comment by giftade** [comment]
Hi @nSedrickm, I won't be able to, I've been really busy with school work and personal stuff, perhaps @teyim can take this up.
I'm really sorry
