### ISSUE TITLE
[staging] Rebooted PC but account remained logged in

### ISSUE THREAD

**Issue by sherlockwisdom** [smswithoutborders/SMSWithoutBorders.com#60]

**Comment by nSedrickm** [comment]
@sherlock this is expected if you didn't logout and your session is still valid (2h)

**Comment by sherlockwisdom** [comment]
Let's reduce that to 30 minutes

**Comment by nSedrickm** [comment]
Its a config you can change on the BE

**Comment by sherlockwisdom** [comment]
There is a security vulnerability here, how is the FE handling it away from the BE?

**Comment by nSedrickm** [comment]
If the user makes any request after their session expires a 401 is thrown and they are logged immediately
