### ISSUE TITLE
Modify Docs to prevent errors during windows project setup

### ISSUE THREAD

**Issue by teyim** [smswithoutborders/SMSWithoutBorders.com#65]
Users will encounter several issues while setting up this project on windows
### issue 1
Windows users will get a `make not recognized as an internal or external command` when trying to run the app locally after installing dependencies..
-**Fix** : Doc should prompt windows users ( with necessary commands) to install make via Chocolatey 

### issue 2
On Windows, an IDE like VS CODE  uses PowerShell as the default terminal, which will give the following error when the `prestart` script runs:
![bandicam 2022-12-19 11-51-28-108](https://user-images.githubusercontent.com/48864977/208409653-d51105a2-fa46-433a-973d-ed00f7676457.jpg)

-**Fix**: prompt Windows users to switch to /use  Command prompt or Git bash terminal

**Comment by teyim** [comment]
@nSedrickm i can open a PR for this

**Comment by nSedrickm** [comment]
Sure thing @teyim. We all work primarily with Linux. How do you plan on approaching this?

**Comment by nSedrickm** [comment]
Good idea, we use bash and shell environments from dev to prod so modifying the script itself won't be ideal.

**Comment by teyim** [comment]
Yes.. I'll open a PR for this, in both this repo and the **SMSWithoutBorders-Dev-FE** repo.

**Comment by teyim** [comment]
@nSedrickm, please kinda review the PR I opened for this.

**Comment by nSedrickm** [comment]
Fixed in #66
